/**
 * Cleans and formats Lua content with proper SB headers while preserving
 * ALL game content: depot keys, manifest IDs, DLC entries, section comments,
 * and inline comments.
 * 
 * Handles Lua files from any source (Morrenus, other bots, or SB itself)
 * by stripping the old header/branding and replacing with SB header.
 */
export function cleanLuaContent(content: string, gameName: string, appId: string): string {
    // Normalize line endings (handle Windows \r\n and old Mac \r)
    const normalized = content.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
    const lines = normalized.split('\n');

    // Known header patterns to strip (case-insensitive)
    const HEADER_PATTERNS = [
        /created by/i,
        /generated by/i,
        /generated lua manifest/i,
        /owner:/i,
        /website:/i,
        /no one has the right/i,
        /personal use and sharing/i,
        /distribute or take credit/i,
        /===+/,
        /^--\s*appid\s+\d+/i,
        /^--\s*name:\s+/i,
        /^--\s*total depots:/i,
        /^--\s*total dlcs:/i,
        /^--\s*shared depots:/i,
        /^--\s*created:/i,
        /morrenus/i,
        /^--\s*\d+'s lua/i,
    ];

    let contentStartIndex = -1;
    let headerEndIndex = -1;

    for (let i = 0; i < lines.length; i++) {
        const trimmed = lines[i].trim();
        if (trimmed === '') continue;

        if (trimmed.startsWith('addappid') || trimmed.startsWith('setManifestid') || trimmed.startsWith('addtoken')) {
            contentStartIndex = i;
            break;
        }

        if (trimmed.startsWith('--')) {
            const isHeaderComment = HEADER_PATTERNS.some(pattern => pattern.test(trimmed));
            if (isHeaderComment) {
                headerEndIndex = i;
                continue;
            }

            if (headerEndIndex >= 0) {
                contentStartIndex = i;
                break;
            }
            continue;
        }
    }

    if (contentStartIndex === -1) {
        contentStartIndex = headerEndIndex >= 0 ? headerEndIndex + 1 : 0;
    }

    const bodyLines = lines.slice(contentStartIndex);
    while (bodyLines.length > 0 && bodyLines[bodyLines.length - 1].trim() === '') {
        bodyLines.pop();
    }
    const bodyContent = bodyLines.join('\n');

    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        timeZoneName: 'short'
    });

    const header = [
        `-- =========================================================`,
        `--  This file was generated by SB manifest.`,
        `--  No one has the right to distribute or take credit for this file.`,
        `--  Personal use and sharing with friends is allowed.`,
        `--  Owner: SB`,
        `-- =========================================================`,
        `-- Generated Lua Manifest by SB manifest`,
        `-- AppID ${appId}`,
        `-- Name: ${gameName}`,
        `-- Updated: ${dateStr}`,
        ``
    ];

    return header.join('\n') + bodyContent + '\n';
}
