/**
 * Cleans and formats Lua content with proper SB headers while preserving
 * ALL game content: depot keys, manifest IDs, DLC entries, section comments,
 * and inline comments.
 * 
 * Handles Lua files from any source (Morrenus, other bots, or SB itself)
 * by stripping the old header/branding and replacing with SB header.
 * 
 * @param {string} content The original Lua content
 * @param {string} gameName The name of the game
 * @param {string} appId The Steam AppID
 * @returns {string} The cleaned and formatted Lua content
 */
export function cleanLuaContent(content, gameName, appId) {
    // Normalize line endings (handle Windows \r\n and old Mac \r)
    let normalized = content.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

    const lines = normalized.split('\n');

    // Find where the actual game content starts.
    // Headers are blocks of comments at the top that contain branding/meta info.
    // We want to KEEP section comments like "-- MAIN APPLICATION", "-- SHARED DEPOTS",
    // "-- DLCS WITHOUT DEDICATED DEPOTS" etc. that come after the header.

    // Known header patterns to strip (case-insensitive)
    const HEADER_PATTERNS = [
        /created by/i,
        /generated by/i,
        /generated lua manifest/i,
        /owner:/i,
        /website:/i,
        /no one has the right/i,
        /personal use and sharing/i,
        /distribute or take credit/i,
        /===+/,                          // Separator lines like =========
        /^--\s*appid\s+\d+/i,           // "-- AppID 1234"
        /^--\s*name:\s+/i,              // "-- Name: Game Name"
        /^--\s*total depots:/i,          // "-- Total Depots: 4"
        /^--\s*total dlcs:/i,            // "-- Total DLCs: 3"
        /^--\s*shared depots:/i,         // "-- Shared Depots: 2"
        /^--\s*created:/i,              // "-- Created: September 29, 2025..."
        /morrenus/i,                     // Morrenus branding
        /^--\s*\d+'s lua/i,             // "-- 1627720's Lua and Manifest..."
    ];

    // Find the content start: everything before the first addappid/setManifestid/addtoken
    // that isn't a section comment we want to keep
    let contentStartIndex = -1;
    let headerEndIndex = -1;

    for (let i = 0; i < lines.length; i++) {
        const trimmed = lines[i].trim();

        // Skip empty lines
        if (trimmed === '') continue;

        // If this is a code line (addappid, setManifestid, addtoken), content begins
        if (trimmed.startsWith('addappid') || trimmed.startsWith('setManifestid') || trimmed.startsWith('addtoken')) {
            contentStartIndex = i;
            break;
        }

        // If this is a comment, check if it's a header comment or a section comment
        if (trimmed.startsWith('--')) {
            const isHeaderComment = HEADER_PATTERNS.some(pattern => pattern.test(trimmed));

            if (isHeaderComment) {
                headerEndIndex = i; // This line is part of the header, mark it
                continue;
            }

            // This is a section comment (like "-- MAIN APPLICATION") — content starts here
            // But only if we're past the header block (i.e., we've seen header comments)
            if (headerEndIndex >= 0) {
                contentStartIndex = i;
                break;
            }

            // If we haven't seen any header patterns yet and this is a comment,
            // it could be either a header line we don't recognize or a section comment.
            // Look ahead: if the next non-empty line is also a comment or header pattern,
            // continue scanning. If it's code, this might be the start.
            continue;
        }
    }

    // If no code was found at all, fall back to keeping everything after header
    if (contentStartIndex === -1) {
        contentStartIndex = headerEndIndex >= 0 ? headerEndIndex + 1 : 0;
    }

    // Extract everything from content start to end, preserving:
    // - Section comments (-- MAIN APPLICATION, -- SHARED DEPOTS, etc.)
    // - Blank lines between sections
    // - Inline comments on code lines (-- Lies of P)
    // - All addappid, setManifestid, addtoken calls
    const bodyLines = lines.slice(contentStartIndex);

    // Trim trailing empty lines but keep internal structure
    while (bodyLines.length > 0 && bodyLines[bodyLines.length - 1].trim() === '') {
        bodyLines.pop();
    }

    const bodyContent = bodyLines.join('\n');

    // Build the new SB header
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        timeZoneName: 'short'
    });

    const header = [
        `-- =========================================================`,
        `--  This file was generated by SB manifest.`,
        `--  No one has the right to distribute or take credit for this file.`,
        `--  Personal use and sharing with friends is allowed.`,
        `--  Owner: SB`,
        `-- =========================================================`,
        `-- Generated Lua Manifest by SB manifest`,
        `-- AppID ${appId}`,
        `-- Name: ${gameName}`,
        `-- Updated: ${dateStr}`,
        `` // Empty line before content
    ];

    return header.join('\n') + bodyContent + '\n';
}